### ISSUE TITLE
windows 10 compability

### ISSUE THREAD

**Issue by moeinrahimi** [Akryum/peeky#31] opened 2021-09-01 13:52 UTC
when I run the test command peeky tries to open a random file next to my tests directory.
my node version: v14.16.1
``` bash
Running tests failed: Error: Cannot find module 'PATH\modules\Personal\test\test-b4J-WIH9g.js'
Require stack:
- F:\projects\karafs\diet-server-v2\node_modules\@peeky\runner\dist\worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.Module._load (PATH\node_modules\node_modules\mock-require\index.js:30:22)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AsyncFunction.runTestFile (PATH\node_modules\@peeky\runner\src\run-test-file.ts:44:5)
```

**Comment by Akryum** [comment] 2021-09-01 13:55
Duplicate of #2

**Closed** 2021-09-01 13:55 UTC
