### ISSUE TITLE
Running tests failed: Error: Cannot find module

### ISSUE THREAD

**Issue by ippatev** [Akryum/peeky#35] opened 2021-09-13 09:14 UTC
ERROR  Running tests failed: Error: Cannot find module '...\test-8WyLrsN4a.js'
Require stack:
- ...\node_modules\@peeky\runner\dist\worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.Module._load (...\node_modules\node_modules\mock-require\index.js:30:22)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AsyncFunction.runTestFile (...\node_modules\@peeky\runner\src\run-test-file.ts:44:5)

**Comment by Akryum** [comment] 2021-09-13 09:45
Duplicate of #2

**Closed by Akryum** 2021-09-13 09:45 UTC
